### ISSUE TITLE
add file config

### ISSUE THREAD

**Issue by icrayix** [MiraculixxT/MCord#2]
add proper file config containing all user specific values for easier contributiing and testing 
LG MfG

**Comment by MiraculixxT** [comment]
I will look into it. (Aka, i'll search a config library to yoink)

**Comment by MiraculixxT** [comment]
Added the original Variables class with placeholder values
https://github.com/MiraculixxT/MCord/blob/master/src/main/kotlin/de/miraculixx/mcord/utils/Variables.kt
